name: Greeting
on:
  fork:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened]
  pull_request_review_comment:
    types: [created]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repo-token: ${{ secrets.COMMUNITY_TOKEN }}
          issue-message: "<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face:"
          pr-message: "<h1>It's great having you contribute to this project</h1> Welcome to the community :nerd_face: Thanks for giving your time to contribute to <b>Typing Test</b> Project."
          footer: 'If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="https://discord.gg/7c3VGDutmS">Discord</a> chat - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.'
